N_TIME = 100
PIXELS = 300
N_ALPHAS = PIXELS
EXACT_RADON_TRANSFORM = "exact_radon_transform"
ALPHAS = "alphas"
EPSILON = 10 ** (-7)
STEPSIZE = 1
TOL_CONV = 10 ** (-5)
DELTA = 7 * 10 ** (-3)
ITERATOR = "Iterator = "
PENALTY_TOL = 10 ** (-6)
SEED = 1
STEPSIZE_TOL = 10 ** (-14)
MAX_ITER_WOLFE = 100
COUNT_UNTIL_CONVERGENCE = 5
LAMBDA_MULTIPLICATION_FACTOR = 10
MOBIUS_REG = 1#10**(-5)

# Problem_dictionary_strings
THETA_RECONSTRUCTED = "Theta reconstructed"
LENGTH_RECONSTRUCTED = "Length reconstructed"
POINT_RECONSTRUCTED = "Point reconstructed"
THETA_INITIAL = "Theta initial"
LENGTH_INITIAL = "Length initial"
POINT_INITIAL = "Point initial"
THETA_REFERENCE = "Theta reference"
THETA_SOLUTION = "Theta solution"
POINT_SOLUTION = "Point solution"
LENGTH_SOLUTION = "Length solution"
BETA_STRING = "Beta"
LAMBDA_STRING = "Lambda"
EPSILON_DERIVATIVE_STRING = "Epsilon for derivative"
DELTA_HEAVISIDE_STRING = "Delta for heaviside"
N_TIME_STRING = "N time"
PIXELS_STRING = "Pixels"
C_1_STRING = "C_1"
C_2_STRING = "C_2"
TAU_STRING = "Tau"
STEPSIZE_STRING = "Step size"
TOL_CONV_STRING = "Tolerance"
ANGLES_STRING = "Angles"
PENALTY_TOL_STRING = "Tolerance penalty"
MAX_LAMDA_STRING = "Max lambda"
NOISE_SIZE_STRING = "Noise size"
NUMBER_OF_FULL_LOOPS_STRING = "Number_of_full_loops"
INITIAL_OBJ_FUNC = "Initial Objective function"
FINAL_OBJ_FUNC = "Final Objective function"
EXPERIMENTS = "Experiments/"